# Ločila

Rabo ločil *Slovenski pravopis* 2001 deli na **skladenjsko** in  **neskladenjsko**. **Skladenjsko** se rabijo na koncu povedi: pika (.), vprašaj (?), klicaj (!), tri pike (...), pomišljaj (–); na koncu dela povedi: vejica (,), podpičje (;), dvopičje (:), tri pike (...), pomišljaj (–); na začetku povedi ali njenega dela: narekovaji („“; »«), odstavčni (alinejni) pomišljaj (–),[^1] tri pike (...); na začetku in koncu povedi ali njenega dela: oklepaj (), dvodelni pomišljaj (–), narekovaji („ “; » «). **Neskladenjsko** se uporabljajo: pika (.), opuščaj ('), vezaj (-), deljaj (-), klicaj (!), vprašaj (?).\

## Pika

### Skladenjska raba

-   Na koncu samostojne ali zložene povedi: *Dolgost našega življenja je kratka.* – *Kosilo se je zavleklo, primanjkovalo je posode.*

-   Končno ločilo se ravna po glavnem stavku: *Ne vem, zakaj sem žalosten.*

-   Citirana poved, piko (končno ločilo) izpustimo: *Podrl je napis »Ne hodi po travi«.*; razen če je za dvopičjem: *Pri Župančiču najdemo tale verz: Veš poet svoj dolg?*

-   Piko zamenjujemo z vejico v premem govoru na koncu dobesednega navedka pred spremnim stavkom: *»Danes je miren dan,«  je rekla Breda.*

### Neskladenjska raba

Piko uporabljamo pri **okrajšanju** besed: *str.*, *dr.*, *t. i.*, *ipd.*, *npr.*, *tj.*, *itd.* (brez pike pišemo simbole *RS*, *EUR*, *m*, *km*, *Fe*, *H~2~0*); za **vrstilnimi** **števniki** in **prislovi**: *prvič*, *drugič*: *na 15. strani*, *5. 12. 2019*, *Jožef II.*, *ob 8. uri zjutraj* = *ob 8^h^ zjutraj*; **med deli številk**, da ločijo enote različnih stopenj: *ob 8.15* = *ob 8^15^*, *150.- EUR*, *132.457* = *132 457*, *3 ·  4*, *merilo 1 : 30.000.000*; **za vsako izpuščeno črko**: *Pojdi v r..!* – *Leta 18.. je Lovro Kvas prišel na Slemenice.*; dveh zaporednih pik (skladenjske in neskladenjske) ne pišemo: *Prišli so vsi: Jakob, Marija, Mojca, Andrej itd.*

## Vprašaj

### Skladenjska raba

-   Za vprašalnim glavnim stavkom: *Kje si bil?* – *Ko drugi grabijo vse dalje, širje, boš, rod, ki bivaš tod, boš v duši čvrst?* – *Ali ne vidiš, da nimam časa?*; *Ne sprašuj kar naprej, kaj smeš, česa ne!*; *Kdo je rekel Vse teče?* – *Čigave so besede Veš, poet, svoj dolg?*; *Kdo je zavpil »Dol z njimi!«.*

-   Na koncu priredja ali proste zveze stavkov, če je zadnji neodvisni stavek vprašalen: *Včeraj, ko sem stala na pragu, je prišel mimo – kaj misliš kdo?*

-   Na koncu vprašalnega dobesednega navedka: *»Kaj je temu vrabcu?«  je vprašala Malči nejevoljno.*

### Neskladenjska raba

Sredi besedila (in sicer v oklepaju) ali na robu besedila ipd. za izražanje dvoma dokončnega izraza ali dela besedila: *Prešeren je bil rojen na (?) Vrbi.*

## Klicaj

### Skladenjska raba

-   Na koncu čustveno obarvane povedi: *Pavel, molči!* – *Na pomoč!*; *Nehajte že s tem svojim To nikakor ni dovoljeno!*; *Nehajte že s tem svojim »To nikakor ni dovoljeno!«!*

-   Na koncu priredja ali proste zveze stavkov, če je zadnji neodvisni stavek vzkličen: *Moj klic raztrgal je vihar; nihče ne bo ga čul nikdar – sam izprašuj se vekomaj, sam si odgovore dajaj!*

-   Na koncu čustveno obarvanih povedi: *Pred leti – da bi se ne bilo zgodilo nikoli! – sem spoznal tega človeka.*

-   Za zvalniki (bolj običajna je raba vejice): *Janez, kam greš?* = *Janez! kam greš?*

-   Za nagovorom v pisnim: *Dragi prijatelj!*

-   Na koncu vzkličnega dobesednega navedka: *»Pavel, molči!«  je prosil oče.*

### Neskladenjska raba

Sredi besedila (in sicer v oklepaju) ali na robu besedila, če hočemo na kaj posebej opozoriti: *Prinesel nam je pepk[^2] (!) in zimskih hrušk.*

## Vejica

### Skladenjska raba

Vejico pišemo:

1.  **med enakovrednimi deli proste ali zložene povedi:**

    a)  **nestavčni enakovredni deli:**

        -   **vezalni** (naštevanje): *Polje, vinograd, gora, morje ...* – *Slovenci so se izseljevali deloma v Nemčijo, deloma v Francijo, deloma v Ameriko.*

        -   **stopnjevalni**: *Ne le ti, temveč tudi tvoj brat pride.* – *Bil je talentiran, celo genialen učenec.*

        -   **ločni**: *Bi kavo, čaj?*

        -   **vzročni** in **posledični**: *Neizkušena, kajti mlada, je odšla v svet.*

        -   **pojasnjevalni**: *Prišel je pozno, šele ob treh.* – *Trst, dne 11. oktobra 1983.* – *Ivan Grohar, Sejalec.*\
            **Posebnosti**:\

        -   Kadar levi prilastek določa celo preostalo BZ, ne pišemo vejice: *dolgi kodrasti lasje*;

        -   Zapis pri datumu: *v nedeljo, 20. maja, ob 17. uri bo ...*

        -   Pri naštevalnih seznamih za enotami, ki niso povedi, lahko vejice opuščamo:\
            [*Obvestijo se:\
            predsednik\
            podpredsednik\
            člani\
            računovodstvo\
            arhiv\
            *]{}

    b)  **pristavčni deli:**

        -   **Vejica je na obeh straneh**: *Pri Prešernu, največjem slovenskem pesniku, so se učili vsi kasnejši pesniški rodovi.* – *Podjetju Mavrica, d. d., grozi stavka.* – *Slovensko narodno gledališče, Opera in balet, ima na sporedu tri nove predstave.*

            -   Na koncu povedi druge vejice ne pišemo: *Oglasil se je Stane Suhadolc, po domače Kovačev.* – *To povest je napisala Zofka Kveder, por. Jelovšek.*

            -   **Posebnost**: Če je lastno ime določilo pred njim stoječe BZ, ga od nje ločimo z vejico, kadar domnevamo, da zveza naslovniku tega imena ne napoveduje samoumevno: *Največji slovenski pesnik, France Prešeren, se je rodil v Vrbi.* = *Največji slovenski pesnik France Prešeren se je rodil v Vrbi.*

    c)  **stavčni enakovredni deli**

        -   **Vezalni**: *Pod nebom ptice letajo, ribe v vodi plavajo, v hostah zamira glas sekire, s polja sejalec gre domov.*

        -   **stopnjevalni**: *Ni se niti zahvalil, kaj šele da bi bil plačal.*

        -   **ločni**: *Zdaj je jokal, zdaj se je smejal.*

        -   **protivni**: *Vse ima, vendar ni zadovoljen.* – *Mimo je šel, in (= vendar) se ni oglasil.* – *Rad ima družbo, še rajši pa (ima) knjigo.*

        -   **vzročni**: *Ne hodi po progi, je nevarno.* – *Odhiteli so pospravljat seno, kajti pripravljalo se je k nevihti.*

        -   **posledični**: *Prosil me je, pa (= zato) sem jim ustegel.* – *Zatri knjigo, in tema se zgrne nad nami.* (= Če nam zatreš knjigo, se tema zgrne nad nami.)

        -   **pojasnjevalni**: *Iz samostana je zvon zavabil, to molijo nune.*

        -   v **bibliografskih** zapisih med enotami: *Milko Kos, Srednjeveška Ljubljana, 1955, 79 strani.*\
            **Pomni**:

        -   Z vejico ločimo tudi vrinjene stavke: *Daleč, ne vem kje, se je oglasil žvižg.* – *Cankar, to vemo, je živel dalj časa na Dunaju.*

    d)  **nestavčno-stavčni enakovredni deli**
        - **Vejice med skladenjsko enakovrednimi deli ne pišemo:**
            -  pred vezalnimi *in*, *pa*, *ter*, ločnimi *ali*, *oziroma*, *bodi(si)*, stopnjevalnimi *ne* – *ne*, *niti* – *niti*, *tako* – *kakor* vejice ne pišemo;
            -   vezalni: *Hana prinese steklenico in kozarce ter šunko.* – *Poiskal je vžigalice in prižgal svečo.*
            -   stopnjevali: *Nisem ne tat ne ubijalec.* – *Društvo se je ohranilo do današnjega dne pa tudi njihova pravila še veljajo.*
            -   ločni: *Ali delaj doma ali pojdi v svet.* – *Ta poročila so bodisi resnična bodisi zlagana.*
            -   Vrinjeni stavki: *Moj prijatelj, tudi jaz imam prijatelja, in njegova žena živita v Kranju*
            -   Kadar sta osebka prirednih stavkov slabo družljiva, pišemo vejico pred *in*: *Komaj je zatisnil oči, se je zbudil, in dan je bil.*
        - **Vejice med skladenjsko enakovrednimi deli ne pišemo:**
            -   kadar posamezne izraze ponavljamo, ne da bi jih v govoru ločili s premori: *Beli so beli češnjevi cvetovi.* – *Perilo je belo belo.* - *Joj joj, kako boli!*
            -   med prirednimi besednimi zvezami z izpuščenim veznikom *in*, *ali*: *na vrat na nos* – *križem kražem* – *hočeš nočeš moraš*.

2.  **med nadrednim in odvisnim stavkom**;

    -   Vejico vedno pišemo: *Ker je deževalo, so ostali doma.* – *Dejal sem jim, da ga ni doma, in jih odslovil.* – *Prej, ko še ni bilo ceste, smo hodili čez vrtove.*

    -   Vejico pišemo, četudi je os. glag. oblika izpuščena: *Še zmeraj kaj dela, čeprav (je) že v letih.* – *Kolikor bo dal on, toliko (bom dal) jaz.* – *Odslovil sem ga, kakor (sem to storil) nerad.*

    **Posebnosti:**

    -   Kadar prideta skupaj dve podredni vezniški besedi, vejico opuščamo: *Le piši materi, da če ne bo denarja, ne boš več stanoval pri nas.* – *Skusili ste, da kdor se iz prvega prenagli, kmalu odneha.*

    -   Kadar prideta skupaj priredni in podredni veznik pred vmesnim odvisnikom, pišemo vejico samo pred prvim veznikom: *Pridem sam, in če bo le mogoče, pripeljem še koga.* – *Votlina je bila suha, in ker je ne doseže nobena sapica, tudi topla.*

        -   Vejico pišemo pred prvo in pred drugo vezniško besedo, kadar priredni veznik zastopa opuščeni nadredni stavek: *Nekaj pa vam obljubim, namreč (to obljubim), da kmalu spet pridem.*

    -   Vejice ne pišemo med deli večbesednega veznika: *Namesto da bi se učil, je lenaril.* – *Kljub temu da je bil bolan, je šel na delo.* – *Rad ga imam, zato ker je tako miren.*

        -   Te vezniki so: *namesto da*, *že ko*, *kljub temu da*, *češ da*, *medtem ko*, *zato ker*, *zato da*, *prej ko*, *tako da*, *toliko da*, *potem ko*, *vtem ko*, *še ko*, *brž ko*, *šele ko*, *s tem da*, *posebno ko*, *zlasti če* itd.

        -   Če prvi del večdelnega veznika prenesemo v nadredni stavek, med veznikoma pišemo vejico: *Utihnil je zato, ker je bil mrtev.* – *Rada ga imam zato, ker je tako miren.* – *Zeblo ga je tako, da se je ves čas tresel.*

    -   Pred primerjalnimi vezniki *kakor*, *kot*, *ko* in stopnjevalnim *tako – kakor* vejice ne pišemo, če za veznikom ne sledi os. glag. oblika: *Ne kaže drugega kakor molčati.* – *Bolje je delati kot govoriti.* – *Več je delal kot govoril.* \[ampak *Moral bi bil več delati, kakor je.*\]

    -   Med izrazi, nastalimi iz stavkov, ki na začetku povedi ali pred kakšnim notranjim stavkom izražajo razmerje govorečega do vsebine povedanega: *Skratka, uspeh je presegel.* – *Sicer pa, kaj bi vam še najprej govoril.* – *Najprej, tole mora ostati med nami.*

    -   Za vmesnim stavkom pred besedo, ki nadomešča opuščeni odvisnik, enak prvemu delu priredja vejico **lahko** pišemo: *Prišel je, sam ni vedel, zakaj (je prišel).* = *Prišel je, sam ni vedel zakaj (je prišel).*

3.  **med polstavkom in preostalim besedilom povedi**;

    -   Kadar je jedro polstavka deležje, deležnik, pridevnik, samostalnik: *Prijazno meketaje vrh skale, sta kozi vabili ovce k sebi.* – *Želeč jim lahko noč, so se poslovili.* – *Sledeč ga je zavrnil, rekoč: »Kaj pa to tebi mar!«* – *Fant pa se je, velik navihanec, pri tem samo muzal.* – *Iz moje mladosti, vse polne ponižanja, se svetijo tiho tvoje oči.*

    -   Vejico lahko pišemo, kadar nedoločniški polstavek lahko razvijemo v os. glag. obliko: *Njegova želja je, postati zdravnik.* = *Njegova želja je postati zdravnik.* – *Postati zdravnik, je njegova želja.* = *Postati zdravnik je njegova želja.*

    -   Če je nedoločniški polstavek v funkciji povedkovega določila ali prilastka, pred njim NI vejice: *Slišala je ptičko peti.* – *Začelo je močno snežiti.* – *Treba je pridno delati.*

    **Posebnosti:**

    -   Kadar je deležje golo (brez dopolnila), ob njem vejico pišemo, če ga razumemo kot polstavek, drugače ne: *Boječ se, se je deklica približala skupini na trati.* ali *Boječ se se je deklica približala skupini na trati.*

    -   Kadar so deležja po nastanku prislovi, jih ne ločimo z vejico od ostalega besedila: *Molče je odšel.* – *Skrivši jih je obiskovala.* – *Boječe se je deklica približala skupini na trati.*

    -   Če so deležniški in pridevniški polstavki levi prilastki, jih ne ločujemo z vejico: *Po sreči hrepeneče (srce je nemirno).* – *(Dokler ptič po drevju leta, ga) v tičnici nastavljena (jed prijazno k sebi vabi).*

4.  **med izpostavljenim stavčnim členom ali dostavkom in preostalim delom povedi**;

    -   **Izpostavek**: ***Sin**, ta ti bo še zagodel!* – *Ali se ga bojiš, **te reve**?* – ***V mojih letih**, takrat je bilo vse drugače.*

    -   **Dostavek**: *Prinesi nam tudi kruha, **črnega**.* – *Prinesi mi sivi plašč, **in rokavice**.* – *Stanuje v eni ljubljanskih občin, **bežigrajski**.*

5.  **med izrazi in stavki, ki niso stavčni členi ali deli priredja oz. podredja**.

    -   **Zvalniki** in **ogovori**: *Gospa, kar po domače.* – *Odloči se že, mevža mevžasta!*

    -   **Samostojno rabljeni medmeti** in medmetne zveze: *O, Janez, kam pa ti?* – *Bum bum bum, je zagrmelo po vratih.* – *Dober dan, kako kaj živite?* – *Križ božji, kakšen pa si!*

        -   Medmeti, ki niso rabljeni samostojno in so **stavčni členi**: *Miška pa smuk v luknjo.* – *Krava reče mu.* – *Reci da in hajdi z mano.*

        -   Med medmetom in zvalnikom ni vejice, če med njima ni premora: *O mati, o domovina!*

    -   **Samostojni členki**: *Da, vse je čisto.* – *Seveda, tega ne tajim.* – *Čez mesec dni ti vrnem, prav gotovo.*

        -   Odvisno od stilnega poudarka: *Tega seveda ne tajim.*

### Neskladenjska raba

-   Seznami: *Molan, Ivan* – *kruh, črni*;

-   Meja med celim in necelim številom: *1,50*;

-   Včasih za označitev milijonic: 52,500.000 EUR.

## Dvopičje

### Skladenjska raba

-   Pojasnilo, naštevanje: *Občna imena so lahko konkretna: lipa, kamen, in abstraktna: mladost, hrepenjenje.* \[dvopičje v teh primerih lahko zamenjamo z vejico in veznikom, npr. *in sicer*, *in to je*, *npr.*\].

    -   Dvopičja ne pišemo pred navedkom, ki je prilastek izraza pred seboj: *Descartesov izrek »Mislim, torej sem«  poznajo vsi, ki so zares izobraženi.*

    -   Pri pristavkih lahko uporabimo tudi vejico ali pomišljaj: *Le eno je potrebno: delo.* = *Le eno je potrebno, delo.* = *Le eno je potrebno – delo.*

-   Po napovednem spremnem stavku pri premem govoru: *Ženska je vprašala: »Kaj bi radi?«* – *Vsi so odgovorili: Da.*

-   Pred stavkom, s katerim pojasnjujemo drug stavek: *Ivan je kakor ura: nikoli ne bo zamudil.*

-   V obrazcih: Ime:        Priimek:

-   Skrajšana napoved: *Foto: arhiv Dela* \[= Fotografija je iz arhiva Dela.\]

### Neskladenjska raba

-   za pomen 'proti': *1 : 2* (ena proti dva), *Slovenija : Avstrija*;

-   za pomen 'deljeno': *4 : 2* (štiri deljeno z dva);

-   za pomen 'v zasprotju z': *lepa* : *lipa* : *lopa*.

## Podpičje

### Skladenjska raba

»Loči posamezne dele povedi krepkeje kot vejica in šibkeje kot pika.«

-   Razmeroma samostojna stavka ali zvezi stavkov iste povedi: *Dokler je človek mlad in krepak, je ves svet njegov; kamor položi trudno glavo, tam je doma; vse mu je prijazno, vse mu odpira vrata in srce.*

-   Sestavne dele priredij: *Ali bi sprejel tudi moj odgovor, ne vem; vem pa, da ga nisem utegnil napisati.*

-   Daljše priredne sestavine z vzporedno skladenjsko zgradbo; tudi pri naštevanju (alineje):
    *Nenaglašeni i se v narečju rad izgubi:*
    *a) v nedoločniku: delat, nosti;*
    *b) v velelniku: nes, nos, pros, krož – nesmo, nosmo, prosmo, krožmo;*
    *c) v deležniku na -l (množina, moški spol): smo (ste, so) delal, prosil.*

-   Različne enorodne skupine naštevanega v istem sistemu: *Iz trgovine je prinesel: sladkor, moko, sol; kremo, zobno pasto, milo; baterijo, žarnico in varovalke.*

-   Dele proreka[^3] v veliki povedi: *Ako imenujemo tiste pisatelje, v katerih se splošnočloveške misli in čuti razodevajo lepi obliki; ki imajo veljavo za zmerom, ne samo za svoj čas; ki so vredni; da se stavijo za zgled prihodnjim: smemo po pravici Prešerna imenovati klasika.*

## Pomišljaj

### Skladenjska raba: Enodelni pomišljaj

-   Namesto vejice, poudarjeno ločuje kakšno besedo ali stavek, lahko kaže na nasprotje med stavkoma: *Prijatelj – to je beseda vseh vrst.* – *Ti meni luč – jaz tebi ključ.*

-   Lahko pred pristavčnim pojasnilom: *Le eno je potrebno – delo.*

-   Nedorečena misel, zamolk (lahko tudi tri pike): *Takoj tiho, če ne –!* – *Bratu bi povedala, pa –*

-   Zaznamuje zvezo med osebkom in povedkom, če je glag. oblika izpuščena: *Mladost – norost.* – *Zmagovalec – Jesenice?*

-   Sprememba skladenjskega naklona: *Včeraj, ko sem stala na pragu, je prišel mimo – kaj misliš?*

-   Namesto narekovajev (t. i. narekovalni pomišljaj):\
    *– Kje si bil? vpraša oče. V šoli?*\
    *– Zakaj?*

### Skladenjska raba: Dvodelni pomišljaj

-   Loči vrinjen stavek od preostalega dela povedi: *S prijateljem – zakaj ne bi imel prijatelja tudi jaz – sva šla počasi po drevoredu.*

-   Kadar je vrinjeni stavek med dvema stavkoma, za drugim pomišljajem lahko pišemo vejico: *Med nami je bil – kako smo bili slepi –, vendar ga nismo spoznali.* = *Med nami je bil – kako smo bili slepi – vendar ga nismo spoznali.*

### Neskladenjska raba

-   Namesto predlogov *od ... do*: *proga Ljubljana–Trst*, *knjiga bo stala od 15–20 EUR*, *str. 425–436*, *v letih 1914–1918*, *prekop Ren–Donava* ipd.

-   Odstavčna alineja (namesto številke ali črke):\
    *Lastna imena se delijo na:*\
    *– osebna,*\
    *– zemljepisna,*\
    *– stvarna.*

-   Nestično med enotami besedila, ki so v kakšnem razmerju (jezikoslovje): *počiti – pokati*, *rumeneti – rumeniti*; *tekma Olimpija – Maribor* = *Olimpija : Maribor* ipd.

-   Matematični *minus* je nestični pomišljaj: *3 – 5 = −2*;

-   Relativna števila: −23 °C

-   Dolgi nestični pomišljaj (—) med povedmi raznih besedil ali iz raznih delov istega besedila: *Moj Mate, jó, moj Mate! — Ti skrivnostni moj cvet, ti roža mogota ...*

## Tri pike

### Skladenjska raba

Tri pike (...) so nestično ločilo.

-   Nedokončana misel (lahko pišemo tudi pomišljaj): *Tja bomo našli pot, kjer nje sinovi si prosti ...*

-   Za izpuščene dele navedkov: *Sem videl, ... da le ptica da ime sloveče.* Da poudarimo, da izpust ni avtorjev, damo tri pike med dve poševnici: /.../

-   Za tremi pikami lahko opustimo končno ločilo: *Grobovi tulijo ....* = *Grobovi tulijo ...*

-   Premor pri dodatnih pojasnilih, dopolnilih: *Srečen sem, ko me ta občutek ... prevzema.*

-   Sprememba skladenjskega naklona: *Tebi se je pač lice privadilo ..., kako bi bila drugače tako mirno pustila!*

-   Dvodelne pike pišemo pred in za vrinjenim stavkom: *Med nami je bil ... kako smo bili slepi ..., vendar ga nismo spoznali.* = *Med nami je bil ... kako smo bili slepi ... vendar ga nismo spoznali.*

### Neskladenjska raba

-   Izpust dela besede: *O, ta sveta prepr...!* (Kadar izpustimo samo 1 ali 2 črki, pišemo le 1 ali 2 piki, ko pa izpustimo 3 ali več črk, pišemo tri stične pike.)

## Vezaj

### Skladenjska in oblikoslovna raba: stični vezaj

-   Priredne zloženke (vezaj nadomešča veznik *in*): *poljsko-ruski slovar*, *črno-bela fotografija*, *Ljutomersko-Ormoške gorice*, *gospodarsko-politične razmere* ipd.

-   Pri podrednih zloženkah, če je prvi del števka ali črka: *25-letnica*, *48-kilometrska proga*, *C-vitaminski*, *TV-drama*, *14-krat* ipd.

-   Osamosvojeni del zloženke: *dvo- in večzložne besede*, *prvo- in drugošolci*, *severo- in jugovzhod* ipd.

-   Med črkovno ali števčno podstavo/osnovo in končnico: *njegovi b-ji so nekam čudni* – *r-ovo znamenje* – *40-a leta* ipd.

-   Med kratico in glasovno končnico: *TAM-a*, *NUK-a*, *OZN-ja* ali *OZN-a* ipd.

-   Za naveznim členkom *le-*: *le-ta*, *le-sem* ipd.

-   V nekaterih tujih imenih/zvezah: Aix-en-Provence, rendez-vous ipd.

-   V filozofskem jeziku: *biti-tu-in-zdaj* ipd.

### Skladenjska in oblikoslovna raba: nestični vezaj

-   Med deloma dvojnega imena: *Šmarje - Sap* = (Šmarje in Sap), *Videm - Dobrepolje* ipd.

-   Med os. imenom in vzdevkom ter med prvotnim in prevzetim priimkom (pri priimkih se opušča): *Josip Murn - Aleksandrov* – *Karel Destovnik - Kajuh* – *Zofka Kveder - Jelovšek* ipd.

    -   Posebnost so tuja (citatna) imena: *Rimski - Korsakov* (citatni imenovalnik) – *Rimskega - Korsakova*

### Neskladenjska in neoblikoslovna raba

-   Za ločevanje zlogov: *za-služ-ek*, *vol-ko-vi* ipd.

-   Za zaznamovanje samostojnih delov besede: predpon (*pre-, pri-, za-*), priponskih obrazil (*-ost*, -oba, -oča), medpon (*-o-, -e-*) ipd.

-   Pri decimalkah zaznamujemo enoto 00 pri zapisu denarnih zneskov: *17 345,– EUR* = *17 345,00 EUR*

-   Pri deljenju besede, ki ima v zapisu vezaj, vezaj prenesemo v naslednjo vrstico.

## Oklepaj

### Skladenjska raba

Oklepaj je načeloma dvodelno ločilo, sestoji iz **uklepaja** in **zaklepaja**. Ločimo okrogle `( )`, poševne `/ /`, pokončne `| |`, zavite `{ }`, oglate `[ ]`, lomljene `⟨ ⟩` oklepaje.

-   Ponazoritve: *Odlomek je pisan v lepem jeziku z rahlimi potezami gorenjščine (zlo, nalaš, kmalo).*

-   Variacije in dopolnitve povedanega: *Svojilne pridevnike na -ov, -ev, -in (iz lastnih imen) pišemo z veliko začetnico.*

-   Vrinjene stavke (lahko tudi pomišljaj ali tri pike): *Med najboljše Jakopičeve slike gre Zeleni pajčolan (nastal nekako 1917).*

-   Vsebinsko drugorodne povedi od drugih povedi: *Govorila so: rebra in mišice prsnega koša, trebušna prepona ... jezik, zobje in ustnice. (Glej sliko.)*

-   Dodatke pišočega v citiranem besedilu: *Kritik pravi dobesedno: »Glavno je, da ima* <u>kaj</u> *povedati: besede, oblike bodo sledile same«  (podčrtal K. Š.).*

-   Dele besede ali besedne zveze, ki so možna sestavina dela besede ali besedila ob oklepaju: *(pravo)pisen*, *učitelj(ica)*, *igrati (na) klavir* ipd.

-   Podatki o virih osnovnega besedila: *Soneti nesreče so bili napisati leta 1832 (Kidrič, Prešeren II, str. 173).*

### Neskladenjska raba

-   Raba v matematiki, jezikoslovju in drugih vedah.V jezikoslovju npr. foneme zapisujemo med poševne oklepaje `/ /`, alofone med oglate `[ ]`, grafeme (črke) med lomljene `⟨ ⟩` ipd.

## Zaklepaj

-   Zaklepaj pišemo ob črkah (redkeje ob številkah) pri naštevalnih enotah, npr.:

 ```text
 Kratice in okrajšave so sestavljene:
  a) iz samih malih črk,
  b) iz samih velikih črk,
  c) iz malih in velikih črk.
  ```

## Poševnica

Poševnica je načeloma stično ločilo.

-   Za pomen 'ali', 'oziroma': *Predpona o-/ob- pomeni 'okoli' ali 'pri'.* – *Koper/Capodistria* ipd.

-   Za pomen 'del enega in drugega': *šolsko leto 2020/21* ipd.

-   Za pomen 'ulomljeno', 'skozi': *500 l/min* – *NUK, Ms 580/69* ipd.

-   V jezikoslovju za mejo med deli besede (brez presledka), povedi ali slovarskega sestavka (s presledki); če gre za različne stopnje, lahko uporabimo tudi dvojno poševnico: *del/a-m* – *Moral je živeti ne samo s telesom, // ampak tudi s fantazijo / in premišljevanjem.*

-   Za zaznamovanje verzov (presledek na obeh straneh): *Sem dolgo upal in se bal, / slovo sem upu, strahu dal, / srce je prazno, srečno ni, / nazaj si up in strah želi.*

## Narekovaj

### Skladenjska raba

V slovenskih besedilih običajno uporabljamo dvojne srednje (» «) ali dvojne spodaj-zgoraj („ ") narekovaje. Znotraj narekovajev uporabljamo drugo vrsto narekovajev, npr. enojne zgornje narekovaje (' ').

-   Dobesedni navedek premega govora ali navedenega (citiranega) besedila: *In sto in sto glasov grmi: »Rešitelj Jefte naj živi!«* – *V zgodovini slovenskega slovstva piše Kidrič: »Najtehtneje so protestantje posegli v kulturni razvoj slovenskih dežel z likajem slovenščine.«*

    -   Narekovaj stoji za končnim ločilom citirane povedi, ki ima pred seboj dvopičje: *Janez mi piše: »Jutri popoldne ob treh.«*

    -   Narekovaj stoji pred končnim ločilo, če je citiran le del povedi: *Po Kidriču je Dalmatinova Biblija naš »prvi literarni vzorec trajne vrednosti«.*

    -   Končno ločilo pišemo pred narekovajem, če je naveden najprej zadnji del ene povedi, tej povedi pa sledi še katera citirana poved: *V uvodu beremo, da je geslo v slovarju »natisnjeno polkrepko. Za njim so razvrščene sorodne besede, tako da sta bolje razvidni moč družine in pomen posameznih obrazil.«*

-   Poseben pomen, položaj ali vrednost besed ali BZ: *To je pa čudna »špraha«.* Za ta namen lahko uporabimo tudi ležeči tisk: To je pa čudna *špraha*.

-   Za imena podjetij, ustanov, umetnostnih del, kadar jih ne bi prepoznali kot lastno ime (zlasti na začetku povedi): *»Tovarna tkanin«  je uspešno podjetje.*

### Neskladenjska raba

-   Za navajanje pomena kakšne besede ali BZ v jezikoslovju, navadno z enojnimi zgornjimi narekovaji: *Tožilnik z nedoločnikom se v latinščini uporablja za glagoli dicendi 'rekanja' in sentiendi 'mišljenja'.*

## Opuščaj

-   Zaznamuje izpust črke ali dela številke: *Da b' uka žeja me iz tvoj'ga sveta speljala ne bila, golj'fiva kača!* – *commedia dell' arte* – *Ste si ogledali sejem Moda '93?*

## Ponavljaj

-   ˝ ali -˝- zaznamuje ponovitev pisne prvine iz vrstice nad seboj:\
    [*33,– EUR\
    112,–˝*]{}

## Deljaj

-   Uporablja se za deljenje besed na koncu vrstice:\
    [*... zgodo-\
    vina ...\
    *]{}

-   Če pri deljenju besede z vezajem ali stičnim pomišljajem pride vezaj ali pomišljaj na konec vrstice, prvega deljaj odrine na začetek nove vrstice, pri pomišljaju pa delaj odpade:\
    [*... Ljubljana\
    –Maribor ...*]{}\
     \
    [*... črno-\
    -bel ...*]{}

## Ločila pri premem govoru

-   Premi govor ima dva dela: **spremni** **stavek** in **dobesedni** **navedek**. Spremni stavek je od dobesednega navedka ločen z dvopičje (če je pred njim), sicer pa z vejico, vprašajem ali klicajem, pomišljajem, tremi pikami itd. (odvisno od naklona dobesednega navedka).

-   Navadno uporabljamo dvoje srednje narekovaje, ločilo na koncu dobesednega navedka ali njegovega dela se piše pred drugim delom narekovaja:

    -   »Kdo je izumil ladijski vijak?«  je vprašal profesor.

    -   »Dež bo,«  je rekla.

    -   »In kdo,«  je vprašal profesor, »je izumil ladijski vijak?«

    -   »Z njim boš hodila,«  sem rekel togotno. »Še tega je bilo treba!«

    -   Togotno sem rekel: »Z njim boš hodila! Še tega je bilo treba!«

[^1]: Pri tipkanju ga lahko nadomešča vezaj (-), [@toporisic_slovenski_2001, člen 229].

[^2]: Mišljeno *tepk*.

[^3]: Prorek = Prvi del vélike povédi (v. stavka). V njem se v obliki priredja neodvisnih stavkov ali stavčij (= podredij) ali odvisnikov navaja vrsta prvin, iz česar potem v poreku sledi določen sklep: *Ko bi se sklicali narodi pred sodni stol, naj se izkažejo, kako so gospodarili z izročenimi talenti, kako se je vsak po svoje udeležil vesoljne omike: smel bi se mali slovenski narod brez strahu prikazati med drugimi z drobnimi bukvicami, katerim se pravi Prešernove poezije.* [@toporisic_enciklopedija_1992 230.]
