# Pisanje skupaj, narazen, z vezajem

## Povzetek pravopisnih pravil

Povzeto po @toporisic_slovenski_2001 in @dobrovoljc_kje_2020.

### Zapis s stičnim vezajem

S stičnim vezajem zapisujemo **priredne (pridevniške) zloženke** [vezaj nadomešča veznik *in*]:

- *varstveno-delovni center* = varstveni in delovni center
- *obveščevalno-varnostna služba* = obveščevalna in varnostna služba
- *slovensko-italijanska meja* = *italijansko-slovenska meja* = slovenska in italijanska meja
- *črno-beli televizor*
- *slovensko-angleški slovar* ≠ *angleško-slovenski slovar*
- *angleško-slovensko-nemško-italijanski slovar*
- *belo-modro-rdeča trobojnica*
- *kulturno-umetniški program*
- *Breznik-Ramovšev pravopis*

S stičnim vezajem zapisujemo tudi **pridevniške izpeljanke**:

- *C-vitamin* = *vitamin C*
- *10-odstotni* = *desetodstotni*
- *C-vitaminski* = *cvitaminski*
- *$\beta$-laktamski antibiotik* = *betalaktamski antibiotik*
- *3,5-kilogramski otrok* = *triinpolkilogramski otrok*
- *1,5-sobno stanovanje* = *enoinpolsobno stanovanje*
- *6-odstoten* = *šestodstoten* = *6-%*

S stičnim vezajem zapisujemo tudi **novejše tvorjenke tipa *samostalnik + samostalnik***:

- novinar-urednik = novinar in hkrati urednik
- *Pred davnimi časi je diplomirala iz estetike in marksizma-leninizma.*
- *Ukrivljeni prostor-čas vpliva na tirnice teles in svetlobe natančno tako kot sila gravitacije.*

### Zapis skupaj

Skupaj zapisujemo **podredne zloženke** (pridevnik + samostalnik):

- *dinarskokraški* ← dinarski kras
- *javnofinančni* ← javne finance
- *umetnostnozgodovinski* ← umetnostna zgodovina
- *turističnoinformacijski* ← turistične informacije
- *socialnovarstveni* ← socialno varstvo
- *jezikovnotehnološki* ← jezikovna tehnologija
- *narodnozabavna* glasba ← = nanašajoč se na narodno zabavo

### Zapis narazen

Narazen zapisujemo zvezo prislova in pridevnika:

- *delovno aktiven* človek
- *premo sorazmeren* delež
- *tržno naravnana* panoga
- *hladno stiskanje* olja
- *gensko spremenjena* hrana
- *družbeno koristno* delo

### Zapis skupaj ali z vezajem (pomenska razlika!)

- *politično-ekonomski* = politični in ekonomski
- *političnoekonomski* = politična ekonomija
- *družbeno-gospodarski* = družbeni in gospodarski
- *družbenogospodarski* = družbeno gospodarstvo
- *socialnoekonosmi* = socialna ekonomija
- *socialno-ekonomski* = socialen in ekonomski

### Barve

- *rdeče-oranžno-rumen*
- *rumenozelen*, *rdečeoranžen*
- *črno-bel* ≠ *črnobel*
